### ISSUE TITLE
Créer les Templates GitHub pour les Réunions

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/brasse-bouillon#58]
#### **Prérequis**
- Compréhension des types de réunions nécessaires au projet (**Kick-off**, **Suivi**, **Validation**).
- Accès au dossier `.github/ISSUE_TEMPLATE/` pour configurer les templates.

---

#### **Description**
Mettre en place des templates GitHub pour standardiser la création d’issues liées aux réunions. Ces templates doivent garantir une documentation homogène et inclure des sections pré-remplies pour les éléments essentiels :
- Participants.
- Ordre du jour.
- Décisions.
- Actions à suivre.
- Questions en suspens.

Ces templates seront utilisés pour :
1. Réunions Kick-off (initialisation).
2. Réunions de Suivi (hebdomadaires ou bimensuelles).
3. Réunions de Validation (fin de phase).

---

##### **1. Identifier les Types de Réunions**
- [x] Dresser la liste des types de réunions à standardiser :
  - **Kick-off** : Alignement sur les objectifs et priorités.
  - **Suivi** : Point régulier pour suivre les progrès.
  - **Validation** : Vérification des livrables en fin de phase.
- [x] Définir les objectifs et éléments essentiels pour chaque type.

##### **2. Rédiger les Templates**
- [x] Créer un fichier YAML pour chaque type dans `.github/ISSUE_TEMPLATE/` :
  - `kickoff_meeting.yml`
  - `followup_meeting.yml`
  - `validation_meeting.yml`
- [x] Inclure les sections suivantes dans chaque template :
  - **Participants** : Liste des participants.
  - **Ordre du jour** : Sujets à discuter.
  - **Décisions** : Résumé des décisions prises.
  - **Actions à suivre** : Tâches définies avec responsables et échéances.
  - **Questions en suspens** : Points ouverts à résoudre.

##### **3. Ajouter les Templates au Dépôt**
- [x] Sauvegarder chaque fichier dans le dossier `.github/ISSUE_TEMPLATE/`.
- [x] Vérifier que les templates apparaissent correctement lors de la création d’une nouvelle issue.

##### **4. Tester les Templates**
- [x] Tester la création d’une issue pour chaque type de réunion.
- [x] Valider que toutes les sections sont bien structurées et opérationnelles.

---

#### **Critères de Validation**
- [x] Les trois templates (Kick-off, Suivi, Validation) sont disponibles et opérationnels.
- [x] Chaque template inclut toutes les sections nécessaires (Participants, Ordre du Jour, Décisions, Actions, Questions).
- [x] Les issues générées à partir des templates s’affichent correctement dans GitHub.

---

#### **Livrables**
1. **Templates GitHub** :
   - `.github/ISSUE_TEMPLATE/kickoff_meeting.yml`
   - `.github/ISSUE_TEMPLATE/followup_meeting.yml`
   - `.github/ISSUE_TEMPLATE/validation_meeting.yml`
2. **Templates testés et validés.**

---

#### **Exemple de Template YAML pour Réunion Kick-off**
```yaml
name: Kick-off Meeting
description: Utilisez ce modèle pour documenter une réunion de kick-off.
title: "[Réunion] Kick-off - Date"
labels: ["meeting", "kick-off"]
body:
  - type: markdown
    attributes:
      value: |
        ## Participants
        - [ ] Nom (Rôle)
        - [ ] Nom (Rôle)

        ## Ordre du Jour
        - [ ] Sujet 1 : Description.
        - [ ] Sujet 2 : Description.

        ## Décisions
        - [ ] Décision 1.
        - [ ] Décision 2.

        ## Actions à Suivre
        - [ ] Action 1 : Responsable, Échéance.
        - [ ] Action 2 : Responsable, Échéance.

        ## Questions en Suspens
        - [ ] Question 1.
        - [ ] Question 2.
```

---

#### **Suggestions**
1. **Ajouter des Labels Automatiques :**
   - Associez des labels spécifiques (`kick-off`, `follow-up`, `validation`) pour faciliter le tri des issues.
2. **Lier les Modèles Markdown :**
   - Ajoutez des liens vers les modèles d’ordre du jour et de compte-rendu dans chaque template.
3. **Iterative Testing :**
   - Rassemblez les retours de l’équipe après une première utilisation et ajustez les templates si nécessaire.
