### ISSUE TITLE
Automatiser l’Archivage des Réunions

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/brasse-bouillon#62]
## **Prérequis**
- Une structure de dossier `docs/meeting_notes/` existante et validée.
- Les modèles de compte-rendu (`summary_template.md`) prêts à être utilisés.

---

## **Description**
Mettre en place un workflow GitHub Actions pour automatiser la génération et l’archivage des comptes-rendus de réunion. Ce workflow créera automatiquement un fichier Markdown dans le dossier `docs/meeting_notes/` lorsqu’une issue de réunion est fermée. Cela garantit un archivage homogène et réduit la charge manuelle liée à la gestion des réunions.

---

### **1. Configurer le Workflow GitHub Actions**
- [x] Créer un fichier YAML pour l’action GitHub dans `.github/workflows/archive_meeting.yml`.
- [x] Définir un déclencheur pour le workflow lorsque :
  - Une issue avec le label `meeting` est fermée.
- [x] Ajouter une étape pour générer un fichier Markdown basé sur le modèle `summary_template.md`.

### **2. Définir le Format de Nommage**
- [x] Standardiser le nom des fichiers pour un archivage clair :
  - Format : `[type]_[YYYY_MM_DD].md`
  - Exemples :
    - `kickoff_meeting_2024_12_21.md`
    - `weekly_meeting_2024_12_28.md`
    - `phase1_validation_meeting_2025_01_05.md`

### **3. Sauvegarder les Fichiers dans le Dossier Approprié**
- [x] Configurer l’action GitHub pour sauvegarder les fichiers dans :
  - `docs/meeting_notes/`.
- [x] Vérifier que le fichier généré respecte la structure et le format standard.

### **4. Tester et Valider le Workflow**
- [x] Tester le workflow avec une issue fictive de type réunion.
- [x] Vérifier que :
  - Le fichier est généré avec le bon contenu.
  - Le fichier est sauvegardé dans le bon dossier avec le bon nom.
- [x] Apporter des corrections si nécessaire après les tests.

---

## **Critères de Validation**
- [x] Workflow GitHub Actions opérationnel et déclenché lors de la fermeture d’une issue de réunion.
- [x] Fichiers Markdown générés respectent le format `[type]_[YYYY_MM_DD].md`.
- [x] Les fichiers sont sauvegardés dans `docs/meeting_notes/` avec le contenu issu du modèle `summary_template.md`.

---

## **Livrables**
1. **Workflow GitHub Actions** :
   - Fichier : `.github/workflows/archive_meeting.yml`
2. **Fichiers Markdown Automatisés** :
   - Exemples :
     - `docs/meeting_notes/kickoff_meeting_2024_12_21.md`
     - `docs/meeting_notes/weekly_meeting_2024_12_28.md`

---

## **Exemple de Fichier YAML pour GitHub Actions**
```yaml
name: Archive Meeting Notes

on:
  issues:
    types: [closed]

jobs:
  archive-meeting:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'meeting')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Meeting Notes
        run: |
          DATE=$(date +%Y_%m_%d)
          TYPE=$(echo "${{ github.event.issue.title }}" | awk '{print tolower($1)}')
          FILENAME="docs/meeting_notes/${TYPE}_meeting_${DATE}.md"
          cp docs/meeting_notes/templates/summary_template.md $FILENAME
          echo "File created: $FILENAME"

      - name: Commit and Push Notes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/meeting_notes/
          git commit -m "Auto-archive meeting notes for issue #${{ github.event.issue.number }}"
          git push
```

---

## **Suggestions**
1. **Validation Collaborative :** Partagez le workflow avec l’équipe pour confirmation qu’il couvre tous les cas d’utilisation.
2. **Automatisation Étendue :** Préparez une action similaire pour générer des agendas à partir d’issues ouvertes.
3. **Évolutivité :** Mettez à jour le workflow pour inclure des options supplémentaires, comme la personnalisation du contenu du fichier.
