### ISSUE TITLE
Automatisation Étendue

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/brasse-bouillon#65]
## **Prérequis**
- Les workflows actuels pour l’archivage des comptes-rendus sont opérationnels.
- La structure documentaire `docs/meeting_notes/` est validée.

---

## **Description**
Étendre les capacités d’automatisation dans le projet pour simplifier davantage les tâches liées aux réunions et à la documentation. Cela inclut la génération automatique d’agendas et la planification d’un rapport global pour récapituler les réunions archivées.

---

### **1. Automatiser la Création d’un Agenda**
- [ ] Configurer un workflow GitHub qui génère automatiquement un fichier `agenda_[YYYY_MM_DD].md` dans `docs/meeting_notes/` lorsque :
  - Une issue avec le label `meeting` est ouverte.
- [ ] Utiliser le modèle `agenda_template.md` comme base pour le fichier généré.
- [ ] Nommer le fichier selon le format standard `[type]_meeting_[YYYY_MM_DD].md`.
- [ ] Ajouter un lien vers le fichier généré dans l’issue associée.

### **2. Planifier un Workflow pour Générer un Rapport Global**
- [ ] Configurer un workflow GitHub pour compiler un rapport mensuel des réunions archivées :
  - Inclure :
    - Le nombre total de réunions tenues.
    - Les décisions clés.
    - Les actions en attente ou en cours.
  - Sauvegarder le rapport dans un fichier `docs/reports/meeting_summary_[YYYY_MM].md`.
- [ ] Définir une structure standard pour le rapport :
  - **Résumé global**
  - **Détails des réunions**
  - **Actions ouvertes**
  - **Questions non résolues**

### **3. Tester et Valider les Automatisations**
- [ ] Tester le workflow d’agenda avec des issues fictives.
- [ ] Tester le workflow de rapport global avec des données fictives.
- [ ] Vérifier que les fichiers générés respectent les standards définis :
  - Contenu conforme au modèle.
  - Nom respectant le format `[type]_[YYYY_MM_DD].md`.

---

## **Critères de Validation**
- [ ] Le workflow d’agenda fonctionne et génère un fichier correct lors de l’ouverture d’une issue `meeting`.
- [ ] Le workflow de rapport global compile les données des comptes-rendus archivés et génère un fichier valide.
- [ ] Les fichiers générés respectent les standards (contenu, nommage, emplacement).
- [ ] Les workflows sont testés et validés avec des données fictives.

---

## **Livrables**
1. **Workflow GitHub Actions** :
   - Workflow pour la génération d’agendas (`agenda_workflow.yml`).
   - Workflow pour la génération de rapports globaux (`report_workflow.yml`).
2. **Fichiers Automatisés** :
   - `docs/meeting_notes/agenda_[YYYY_MM_DD].md`
   - `docs/reports/meeting_summary_[YYYY_MM].md`

---

## **Exemple de Workflow YAML pour les Agendas**
```yaml
name: Generate Meeting Agenda

on:
  issues:
    types: [opened]

jobs:
  generate-agenda:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'meeting')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Agenda File
        run: |
          DATE=$(date +%Y_%m_%d)
          TYPE=$(echo "${{ github.event.issue.title }}" | awk '{print tolower($1)}')
          FILENAME="docs/meeting_notes/${TYPE}_meeting_${DATE}.md"
          cp docs/meeting_notes/templates/agenda_template.md $FILENAME
          echo "File created: $FILENAME"

      - name: Commit and Push Agenda
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/meeting_notes/
          git commit -m "Auto-generate meeting agenda for issue #${{ github.event.issue.number }}"
          git push
```

---

## **Suggestions**
1. **Rapport Mensuel Automatisé** :
   - Ajouter un résumé des actions ouvertes pour améliorer la clarté des prochaines étapes.
2. **Suivi des Actions :**
   - Intégrer un système de notification ou une liste des tâches non complétées dans le rapport global.
3. **Documentation :**
   - Ajouter une section dans le fichier `README.md` pour expliquer ces nouveaux workflows.
